version: "3"

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: simple-transaction
    container_name: simple-transaction-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:cached
    networks:
      - simple-transaction

  db:
    image: mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
    container_name: simple-transaction-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simple-transaction
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - simple-transaction

  nginx:
    image: nginx:alpine
    container_name: simple-transaction-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - simple-transaction

  redis:
    image: redis:alpine
    container_name: simple-transaction-redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
    - ./data/redis:/data
    ports:
      - "8002:6379"
    networks:
      - simple-transaction

networks:
  simple-transaction:
    driver: bridge